export const directoryActionTypes = {
    FETCH_DIR_COLLECTIONS_START:'FETCH_DIR_COLLECTIONS_START',
    FETCH_DIR_COLLECTIONS_SUCCESS:'FETCH_DIR_COLLECTIONS_SUCCESS',
    FETCH_DIR_COLLECTIONS_ERROR:'FETCH_DIR_COLLECTIONS_ERROR',
}